@url_base = http://localhost:5212/api/funcionarios


### CRIAR USUARIO
POST {{url_base}}/registrar
Content-Type: application/json

{
    "Nome": "pedro",
    "Cargo": "Gerente",
    "CPF": "06376251960",
    "Email": "user@gmail.com",
    "Senha": "admin123",
    "Telefone": "(41) 9999-9999",
    "DataAdmissao": "2025-11-03",
    "Salario": 4000.00
}


### 3. Listar Funcionários
GET {{url_base}}/listar


### 4. Buscar Funcionário por ID
GET {{url_base}}/buscar/6

### 5. Atualizar Funcionário (Admin)
PUT {{url_base}}/atualizar/1
Content-Type: application/json

{
    "Id":1,
    "Nome": "Gerente Teste Atualizado",
    "Cargo": "Gerente",
    "CPF": "06376251960",
    "Email": "user@gmail.com",
    "Telefone": "(41) 98410-8182",
    "DataAdmissao": "2025-05-12T00:00:00",
    "Salario": 10000.00
}

### 6. Deletar Funcionário
DELETE {{url_base}}/deletar/4


