@url_base = http://localhost:5212/api/funcionarios


### 1. Testar Conexão Básica (sem autenticação)
POST {{url_base}}/registrar
Content-Type: application/json

{
    "Nome": "Melo",
    "Cargo": "User",
    "CPF": "987654321",
    "Email": "melo@gmail.com",
    "Telefone": "(41) 88888-8888",
    "DataAdmissao": "2025-05-19",
    "Salario": 4000
}


### 3. Listar Funcionários
GET {{url_base}}/listar


### 4. Buscar Funcionário por ID
GET {{url_base}}/buscar/6

### 5. Atualizar Funcionário (Admin)
PUT {{url_base}}/atualizar/9
Content-Type: application/json

{
    "Id":9,
    "Nome": "User Teste Atualizado",
    "Cargo": "Sócio",
    "CPF": "123456789",
    "Email": "melo_update@petshop.com",
    "Telefone": "(11) 98888-8888",
    "DataAdmissao": "2025-05-12T00:00:00",
    "Salario": 10000.00
}

### 6. Deletar Funcionário
DELETE {{url_base}}/deletar/7


